name: modular
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev
publish_to: 'none'

# Versioning
version: 1.0.0+1

# Environment (specify compatible Dart SDK versions)
environment:
  sdk: ">=3.5.4 <4.0.0"

# Dependencies
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3

# Development dependencies (e.g., for tests or linting)
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# Flutter-specific settings
flutter:
  uses-material-design: true

  # Assets section: Add your images and other files here
  assets:
    - assets/shelf.png
    - assets/Rectangle.png
    - assets/LOGO.png
    - assets/Title.png
    - assets/Close Button.png
    - assets/Frame 4.png
    - assets/MODULAR.png
    - assets/Welcome - 2.png
    - assets/topPicture.png
    - assets/ModularRED.png
    - assets/PenPicture.png
    - assets/Sketchbook.png
    - assets/Notebook.png
    - assets/NotebookNew.png
    - assets/MachinePicture.png
